apiVersion: batch/v1
kind: CronJob
metadata:
  name: rotator
  labels:
    app: jwt-rotator
    component: security
spec:
  # Run every 5 minutes for testing
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: jwt-rotator
            component: security
        spec:
          serviceAccountName: rotator
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            fsGroup: 65532
          containers:
          - name: rotator
            image: docker.io/library/rotator:local
            imagePullPolicy: Never
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
            securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
            env:
            - name: SECRET_NAME
              value: "jupyter-k8s-authmiddleware-secrets"
            - name: SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMBER_OF_KEYS
              value: "3"
            - name: DRY_RUN
              value: "false"
